/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bank;

import static java.lang.Double.parseDouble;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DepositView extends javax.swing.JPanel {

    private Connection connect; 
    
    private ArrayList<Account> list; 
    
    public DepositView() {
        initComponents();
    }
    
    public void setList(ArrayList<Account> accountlist){
        list = accountlist;
    }
    
    public DepositView(ArrayList<Account> accountList) {
        initComponents();
        
        list = new ArrayList<Account>();
        for(Account i : accountList){
            list.add(i);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        montantText = new javax.swing.JTextField();
        depositButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        numberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel2.setText("Account Number :");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel4.setText("Montant :");

        montantText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montantTextActionPerformed(evt);
            }
        });

        depositButton.setText("Deposit");
        depositButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositButtonMouseClicked(evt);
            }
        });
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MAKE DEPOSIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberText))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(montantText, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(montantText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextActionPerformed

    private void montantTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montantTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montantTextActionPerformed

    private void depositButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositButtonMouseClicked

        /*String number = this.numberText.getText();
        String montant = this.montantText.getText();
        if(number.isEmpty() || montant.isEmpty()){
            JOptionPane.showMessageDialog(this, "All field is required",number, HEIGHT);
        }else{
            try{
                Double montante = parseDouble(montant);
                boolean check = false;
                for(Account account : list){
                    if(account.number.equals(number)){
                        
                        if(montante<=0){
                            JOptionPane.showMessageDialog(this,"Amount Invalide");
                            check = true;
                        }else{
                            double n = account.deposit(montante);
                            JOptionPane.showMessageDialog(this,"Actual Solde : "+n);
                            this.numberText.setText("");
                            this.montantText.setText("");
                            check = true;
                        }
                        break;
                    }
                }
                if(!check){
                    JOptionPane.showMessageDialog(this," Account Number Invalid");
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Amount Invalid");
            }
        }*/
        if(this.montantText.getText().isEmpty() || this.numberText.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "All field is required");
        }else{
            
            try {
                connect = new DBConnection().open();
                Statement stmt = connect.createStatement();
                String req="SELECT Number,Solde FROM Accounts";
                ResultSet res = stmt.executeQuery(req);
                boolean bool =false;

                Double montant = parseDouble(this.montantText.getText()); 
                if(montant<=0){
                    JOptionPane.showMessageDialog(this, "Amount Invalid");
                }else{
                    while(res.next()){
                        if(res.getString(1).equals(this.numberText.getText())){
                            Double solde = res.getDouble(2);
                            req = "UPDATE Accounts SET Solde="+(solde+montant)+" WHERE Number = "+res.getString(1);
                            PreparedStatement pst = connect.prepareStatement(req);
                            pst.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Your Solde is :"+(solde+montant));
                            this.numberText.setText("");
                            this.montantText.setText("");
                            bool = true;
                            break;
                        }
                    }
                }

                if(!bool){
                    JOptionPane.showMessageDialog(this, "Account Number not exist");
                }


            } catch (SQLException ex) {
                Logger.getLogger(DepositView.class.getName()).log(Level.SEVERE, null, ex);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Amount invalid");
            }
        }
        
        
        
        
    }//GEN-LAST:event_depositButtonMouseClicked

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField montantText;
    private javax.swing.JTextField numberText;
    // End of variables declaration//GEN-END:variables
}
