/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bank;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


public class PayView extends javax.swing.JPanel {

    private Connection connect;
    
    private ArrayList<Account> list;
    
    public PayView() {
        initComponents();
    }
    
    public PayView(ArrayList<Account> AccountList){
        initComponents();
        list = new ArrayList<Account>();
        for(Account account : AccountList){
            list.add(account);
        }
        if(this.payList.getSelectedItem().toString().equals("All")){
            this.loanNumber.setEditable(false);
        }else{
            this.loanNumber.setEditable(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        numberText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loanNumber = new javax.swing.JTextField();
        payBoutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        payList = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel2.setText("Account Number:");

        numberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel4.setText("Loan Number");

        loanNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanNumberActionPerformed(evt);
            }
        });

        payBoutton.setText("Pay");
        payBoutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payBouttonMouseClicked(evt);
            }
        });
        payBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBouttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel1.setText("Pay");

        payList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Specified" }));
        payList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payListMouseClicked(evt);
            }
        });
        payList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payListActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PAY LOAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(payBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(loanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(payList, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(payBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextActionPerformed

    private void loanNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanNumberActionPerformed

    private void payBouttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBouttonMouseClicked
        /*String number = this.numberText.getText();
        String loan = this.loanNumber.getText();
        int num=1;
        String text="";
        if(this.payList.getSelectedItem().toString().equals("All")){
            if(number.isEmpty()) JOptionPane.showMessageDialog(this, "Account Number required", loan, HEIGHT);
            else{
                boolean check=false;
                for(Account i : list){
                    if(i.getNumber().equals(number)){
                        i.payYourLoans();
                        for(Loan j : i.getLoan()){
                            text+="\n Pay "+ num+" with amount : "+j.getAmount();
                            //JOptionPane.showMessageDialog(this, "\t All Pay : \n Pay "+ num+" with amount : "+j.getAmount());
                            num++;
                        }
                            JOptionPane.showMessageDialog(this,text);
                            check = true;
                    }
                }
                if(!check){
                    JOptionPane.showMessageDialog(this,"Account Number Invalid");
                }
            }
            
        }else{
            try{
                int loanNum = parseInt(loan);

                for(Account i : list){
                    if(i.getNumber().equals(number)){
                        ArrayList<Loan> loans = i.getLoan();
                         if(loanNum<=0 || loanNum>loans.size()){
                            JOptionPane.showMessageDialog(this,"Loan Number Invalid");
                         }else{
                             loans.get(loanNum).rembourse();
                              JOptionPane.showMessageDialog(this, "\t All Pay : \n Pay "+ loanNum+" with amount : "+loans.get(loanNum-1).getAmount());
                         }
                    }
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Loan Number Invalid");
            }
        }*/
        
        String number = this.numberText.getText();
        String loan = this.loanNumber.getText();
        
        if(this.payList.getSelectedItem().toString().equals("All")){
            if(this.numberText.getText().isEmpty()) JOptionPane.showMessageDialog(this, "Account Number required");
            else{
                try {
                    connect = new DBConnection().open();
                    Statement stmt = connect.createStatement();
                    String req="SELECT Amount,Number,Mensuality FROM Loan";
                    ResultSet res = stmt.executeQuery(req);
                    boolean bool =false;

                    //Double montant = parseDouble(this.montantText.getText()); 

                        while(res.next()){
                            if(res.getString(2).equals(this.numberText.getText())){
                                Double solde = res.getDouble(1);
                                Double mensu = res.getDouble(3);
                                Double sum =(solde-mensu);
                                if(sum<=0) sum=0d;
                                req = "UPDATE Loan SET Amount="+sum+" WHERE Number = "+res.getString(2);
                                PreparedStatement pst = connect.prepareStatement(req);
                                pst.executeUpdate();
                                JOptionPane.showMessageDialog(this, "Operation done");
                                this.numberText.setText("");
                                this.loanNumber.setText("");
                                bool = true;
                            }
                        }

                    if(!bool){
                        JOptionPane.showMessageDialog(this, "No Loan for this Account Number");
                    }


                } catch (SQLException ex) {
                    Logger.getLogger(DepositView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            try {
                connect = new DBConnection().open();
                Statement stmt = connect.createStatement();
                String req="SELECT * FROM Loan ";
                ResultSet res = stmt.executeQuery(req);
                boolean bool =false;

                //Double montant = parseDouble(this.montantText.getText()); 
                    int n =parseInt(this.loanNumber.getText());
                    while(res.next()){
                        if(res.getString(4).equals(this.numberText.getText()) && res.getInt(1)==n){
                            Double solde = res.getDouble(2);
                            Double mensu = res.getDouble(3);
                            req = "UPDATE Loan SET Amount="+(solde-mensu)+" WHERE Number = "+res.getString(4)+" AND id="+res.getString(1);
                            PreparedStatement pst = connect.prepareStatement(req);
                            pst.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Operation done");
                            this.numberText.setText("");
                            this.loanNumber.setText("");
                            bool = true;
                        }
                    }

                if(!bool){
                    JOptionPane.showMessageDialog(this, "Account Number Or Loan id not exist");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(DepositView.class.getName()).log(Level.SEVERE, null, ex);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Loan Number invalide");
            }
        }
        
    }//GEN-LAST:event_payBouttonMouseClicked

    private void payBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBouttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payBouttonActionPerformed

    private void payListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payListMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_payListMouseClicked

    private void payListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payListActionPerformed
        // TODO add your handling code here:
        if(this.payList.getSelectedItem().toString().equals("All")){
            this.loanNumber.setEditable(false);
        }else{
            this.loanNumber.setEditable(true);
        }
    }//GEN-LAST:event_payListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField loanNumber;
    private javax.swing.JTextField numberText;
    private javax.swing.JButton payBoutton;
    private javax.swing.JComboBox<String> payList;
    // End of variables declaration//GEN-END:variables

}
