/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bank;

import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author angelo
 */
public class PayView extends javax.swing.JPanel {

    /**
     * Creates new form PayView
     */
    private ArrayList<Account> list;
    
    public PayView() {
        initComponents();
    }
    
    public PayView(ArrayList<Account> AccountList){
        initComponents();
        list = new ArrayList<Account>();
        for(Account account : AccountList){
            list.add(account);
        }
        if(this.payList.getSelectedItem().toString().equals("All")){
            this.loanNumber.setEditable(false);
        }else{
            this.loanNumber.setEditable(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        numberText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loanNumber = new javax.swing.JTextField();
        payBoutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        payList = new javax.swing.JComboBox<>();

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel2.setText("Number");

        numberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel4.setText("Loan Number");

        loanNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanNumberActionPerformed(evt);
            }
        });

        payBoutton.setText("Pay");
        payBoutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payBouttonMouseClicked(evt);
            }
        });
        payBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBouttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel1.setText("Pay Type");

        payList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Specified" }));
        payList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payListMouseClicked(evt);
            }
        });
        payList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(payBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(loanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(payList, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(payBoutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextActionPerformed

    private void loanNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanNumberActionPerformed

    private void payBouttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBouttonMouseClicked
        String number = this.numberText.getText();
        String loan = this.loanNumber.getText();
        int num=1;
        String text="";
        if(this.payList.getSelectedItem().toString().equals("All")){
            if(number.isEmpty()) JOptionPane.showMessageDialog(this, "Account Number required", loan, HEIGHT);
            else{
                boolean check=false;
                for(Account i : list){
                    if(i.getNumber().equals(number)){
                        i.payYourLoans();
                        for(Loan j : i.getLoan()){
                            text+="\n Pay "+ num+" with amount : "+j.getAmount();
                            //JOptionPane.showMessageDialog(this, "\t All Pay : \n Pay "+ num+" with amount : "+j.getAmount());
                            num++;
                        }
                            JOptionPane.showMessageDialog(this,text);
                            check = true;
                    }
                }
                if(!check){
                    JOptionPane.showMessageDialog(this,"Account Number Invalid");
                }
            }
            
        }else{
            try{
                int loanNum = parseInt(loan);

                for(Account i : list){
                    if(i.getNumber().equals(number)){
                        ArrayList<Loan> loans = i.getLoan();
                         if(loanNum<=0 || loanNum>loans.size()){
                            JOptionPane.showMessageDialog(this,"Loan Number Invalid");
                         }else{
                             loans.get(loanNum).rembourse();
                              JOptionPane.showMessageDialog(this, "\t All Pay : \n Pay "+ loanNum+" with amount : "+loans.get(loanNum-1).getAmount());
                         }
                    }
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"Loan Number Invalid");
            }
        }
        
    }//GEN-LAST:event_payBouttonMouseClicked

    private void payBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBouttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payBouttonActionPerformed

    private void payListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payListMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_payListMouseClicked

    private void payListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payListActionPerformed
        // TODO add your handling code here:
        if(this.payList.getSelectedItem().toString().equals("All")){
            this.loanNumber.setEditable(false);
        }else{
            this.loanNumber.setEditable(true);
        }
    }//GEN-LAST:event_payListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField loanNumber;
    private javax.swing.JTextField numberText;
    private javax.swing.JButton payBoutton;
    private javax.swing.JComboBox<String> payList;
    // End of variables declaration//GEN-END:variables

}
